name: deploy

on:
  push:
    branches:
      - main
      - push-images-to-ecr#5

env:
  AWS_REGION: ap-northeast-1

jobs:
  deploy:
    name: Deploy app to AWS Fargate
    runs-on: ubuntu-latest

    # AWS認証情報の設定
    steps:
      - name: Configure aws credentials for prod
        # if: github.ref == 'refs/heads/main'
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.PROD_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.PROD_AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}
          
          # Assume Roleする対象のIAMロールのARNの指定と権限の有効期間を指定
          role-to-assume: ${{ secrets.PROD_AWS_ASSUME_ROLE_ARN }}
          role-duration-seconds: 1800
          